# Generated by Django 5.2.4 on 2025-08-15 05:42

import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("headline", models.CharField(blank=True, max_length=140)),
                ("about", models.TextField(blank=True)),
                ("location", models.CharField(blank=True, max_length=120)),
                ("experiences", models.JSONField(blank=True, default=list)),
                ("links", models.JSONField(blank=True, default=list)),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, null=True, upload_to=users.models.avatar_upload_path
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
