# Generated by Django 5.2.4 on 2025-08-15 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="avatar",
        ),
        migrations.AddField(
            model_name="profile",
            name="avatar_blob",
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="avatar_content_type",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="avatar_filename",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="avatar_size",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
