# Generated by Django 5.2.4 on 2025-08-16 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_profile_avatar_profile_avatar_blob_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="full_name",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
